allow CDN to be configured
bharel/mkdocs-render-swagger-plugin pull request #10
Opened 2021-03-12 12:56 UTC by Preisschild

closes #1

2021-03-14 18:28 UTC, bharel requested changes
Let's play nice with the URLs 🙂 
You can add all suggestions in a batch if you wish.

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +    extra_css = config.get('extra_css')
```suggestion
    extra_css = config.get('extra_css', [])
```

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +        if os.path.basename(lib) == 'swagger-ui-bundle.js':
```suggestion
        if os.path.basename(urllib.parse.urlparse(lib).path) == 'swagger-ui-bundle.js':
```

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +        if os.path.basename(css) == 'swagger-ui.css':
```suggestion
        if os.path.basename(urllib.parse.urlparse(css).path) == 'swagger-ui.css':
```

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +import os
```suggestion
import os
import urllib.parse
```

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +            lib_swagger['css'] = css
```suggestion
            lib_swagger['css'] = css
            break
```

2021-03-14 18:28 UTC, bharel commented on render_swagger.py
> +            lib_swagger['js'] = lib
```suggestion
            lib_swagger['js'] = lib
            break
```

2021-03-14 19:40 UTC, Preisschild commented
Great suggestions.

Thanks for the review!

2021-03-14 22:47 UTC, bharel approved these changes

2021-03-14 22:47 UTC, merged

2021-03-14 22:51 UTC, bharel commented
@Preisschild I'll update the version to 0.0.2 so you'll use it if you wish.

We still need some tests before we go stable. To be honest, I'm not sure how to test this together with MKDocs output.
Probably won't be too easy.

2021-03-15 06:47 UTC, Preisschild commented
We could use bats to create cli level end to end tests.

The [mkdocs-monorepo-plugin](https://github.com/backstage/mkdocs-monorepo-plugin) does this and it seems to work fairly well